epam/DLab

infrastructure-provisioning/src/general/lib/os/debian/ssn_lib.py, infrastructure-provisioning/src/general/lib/os/redhat/ssn_lib.py, infrastructure-provisioning/src/ssn/scripts/configure_mongo.py, infrastructure-provisioning/src/ssn/scripts/configure_ui.py, infrastructure-provisioning/src/ssn/scripts/resource_status.py, infrastructure-provisioning/src/ssn/templates/ssn.yml
Remove hardcoded mongodb admin password.
=> Feature epmcbdccss 1209

infrastructure-provisioning/src/deeplearning/Dockerfile, infrastructure-provisioning/src/deeplearning/scripts/configure_deep_learning_node.py, infrastructure-provisioning/src/general/lib/os/debian/notebook_lib.py, infrastructure-provisioning/src/general/scripts/aws/deeplearning_configure.py
Added GitWeb installation to deeplearning template
=> Feature epmcbdccss 1218

services/security-service/src/main/java/com/epam/dlab/auth/core/LoginStep.java, services/security-service/src/main/java/com/epam/dlab/auth/core/UserInfoBuilder.java, services/security-service/src/main/java/com/epam/dlab/auth/resources/LdapAuthenticationService.java, services/security-service/src/test/java/com/epam/dlab/auth/core/LoginConveyorTest.java
the keys were still verified even when the aws login was disabled.
=> fixed issue related to aws key verification in case of disabled aws login

README.md, infrastructure-provisioning/src/ssn/scripts/backup.py, infrastructure-provisioning/src/ssn/scripts/configure_ssn_node.py, infrastructure-provisioning/src/ssn/scripts/restore.py
=> [EPMCBDCCSS-1233]: Backup and restore scripts

infrastructure-provisioning/src/general/lib/aws/actions_lib.py, infrastructure-provisioning/src/general/lib/aws/meta_lib.py, infrastructure-provisioning/src/general/lib/os/fab.py, infrastructure-provisioning/src/general/scripts/aws/common_configure_analytic_tool.py, infrastructure-provisioning/src/general/scripts/aws/common_create_instance.py, infrastructure-provisioning/src/general/scripts/aws/common_prepare_hadoop_cluster.py, infrastructure-provisioning/src/general/scripts/aws/common_prepare_notebook.py, infrastructure-provisioning/src/general/scripts/aws/common_start_notebook.py, infrastructure-provisioning/src/general/scripts/aws/deeplearning_configure.py, infrastructure-provisioning/src/general/scripts/aws/edge_configure.py, infrastructure-provisioning/src/general/scripts/aws/edge_prepare.py, infrastructure-provisioning/src/general/scripts/aws/edge_start.py, infrastructure-provisioning/src/general/scripts/aws/edge_terminate.py, infrastructure-provisioning/src/general/scripts/aws/jupyter_configure.py, infrastructure-provisioning/src/general/scripts/aws/rstudio_configure.py, infrastructure-provisioning/src/general/scripts/aws/ssn_configure.py, infrastructure-provisioning/src/general/scripts/aws/tensor_configure.py, infrastructure-provisioning/src/general/scripts/aws/zeppelin_configure.py, infrastructure-provisioning/src/ssn/scripts/upload_response_file.py
- able to rename all DALB resources
=> [EPMCDLAB-726]: use infrastructure Tag instead of "Name" Tag at filters

infrastructure-provisioning/src/general/scripts/os/ipynb_output_filter.py
Changed git filter only for execution counter and metadata, output data will be also committed.
=> [feature-EPMCDLAB759v2]: Added git filter for ipynb files

infrastructure-provisioning/src/general/conf/dlab.ini, infrastructure-provisioning/src/general/lib/os/debian/notebook_lib.py, infrastructure-provisioning/src/rstudio/description.json
Updated RStudio from 1.0.136 to 1.0.143 and latest R for debian platform.
=> [feature-EPMCDLAB-820]: Added new R and RStudio

services/self-service/src/main/resources/webapp/src/app/reporting/reporting-grid/reporting-grid.component.css, services/self-service/src/main/resources/webapp/src/app/reporting/reporting-grid/reporting-grid.component.html, services/self-service/src/main/resources/webapp/src/app/reporting/reporting-grid/reporting-grid.component.ts, services/self-service/src/main/resources/webapp/src/app/reporting/toolbar/toolbar.component.ts, services/self-service/src/main/resources/webapp/src/app/resources/exploratory/install-libraries/install-libraries.component.css
Fixed report page rendering on Microsoft Edge
=> Bugfix EPMCDLAB-827

infrastructure-provisioning/src/ssn/scripts/backup.py, infrastructure-provisioning/src/ssn/scripts/restore.py
Fixed comma separated keys and certs backup.
Fixed backup script to copy jars and symlinks.
Fixed authorization to MongoDB in restore script
=> [bug-EPMCDLAB-885]: Fixed backup and restore scripts

services/self-service/src/main/resources/webapp/src/app/resources/resources-grid/resources-grid.component.css, services/self-service/src/main/resources/webapp/src/app/shared/form-controls/dropdown-list/dropdown-list.component.html, services/self-service/src/main/resources/webapp/src/app/shared/form-controls/multi-select-dropdown/multi-select-dropdown.component.css, services/self-service/src/main/resources/webapp/src/app/shared/form-controls/multi-select-dropdown/multi-select-dropdown.component.html, services/self-service/src/main/resources/webapp/src/app/shared/modal-dialog/confirmation-dialog/confirmation-dialog.component.html, services/self-service/src/main/resources/webapp/src/app/shared/modal-dialog/modal.component.css, services/self-service/src/main/resources/webapp/src/app/shared/navbar/navbar.component.css, services/self-service/src/main/resources/webapp/src/app/shared/navbar/navbar.component.html, services/self-service/src/main/resources/webapp/src/styles.css
replaced old types icons with material; 
added hover effects for navigation bar;
=> feature EPMCDLAB-417

services/self-service/src/main/resources/webapp/src/app/shared/form-controls/multi-select-dropdown/multi-select-dropdown.component.css, services/self-service/src/main/resources/webapp/src/app/shared/form-controls/multi-select-dropdown/multi-select-dropdown.component.html
unified lettering on the filter rows
=> Bugfix EPMCDLAB-957

services/self-service/src/main/resources/webapp/src/app/reporting/toolbar/toolbar.component.css
Fixed broken calendar grid on "Reporting" page in MS Edge
=> Bugfix EPMCDLAB-956

services/self-service/src/main/resources/webapp/src/app/reporting/reporting-grid/reporting-grid.component.ts, services/self-service/src/main/resources/webapp/src/app/resources/billing/cost-details-dialog/cost-details-dialog.component.html, services/self-service/src/main/resources/webapp/src/app/resources/billing/cost-details-dialog/cost-details-dialog.component.ts, services/self-service/src/main/resources/webapp/src/app/resources/computational/computational-resource-create-dialog/computational-resource-create-dialog.component.html, services/self-service/src/main/resources/webapp/src/app/resources/computational/detail-computational-resources/detail-computational-resources.component.html, services/self-service/src/main/resources/webapp/src/app/resources/computational/detail-computational-resources/detail-computational-resources.component.ts, services/self-service/src/main/resources/webapp/src/app/resources/exploratory/detail-dialog/detail-dialog.component.html, services/self-service/src/main/resources/webapp/src/app/resources/exploratory/detail-dialog/detail-dialog.component.ts, services/self-service/src/main/resources/webapp/src/app/resources/exploratory/exploratory-environment-create-dialog/exploratory-environment-create-dialog.component.html, services/self-service/src/main/resources/webapp/src/app/resources/exploratory/exploratory-environment-create-dialog/exploratory-environment-create-dialog.component.ts, services/self-service/src/main/resources/webapp/src/app/resources/resources-grid/resources-grid.component.css, services/self-service/src/main/resources/webapp/src/app/resources/resources-grid/resources-grid.component.html, services/self-service/src/main/resources/webapp/src/app/resources/resources-grid/resources-grid.component.ts, services/self-service/src/main/resources/webapp/src/dictionary/aws.dictionary.ts, services/self-service/src/main/resources/webapp/src/dictionary/azure.dictionary.ts, services/self-service/src/main/resources/webapp/src/dictionary/gcp.dictionary.ts, services/self-service/src/main/resources/webapp/src/dictionary/global.dictionary.ts
[EPMCDLAB-989]: added dictionaries for different clouds
=> Feature EPMCDLAB-989

infrastructure-provisioning/src/deeplearning/scripts/configure_deep_learning_node.py, infrastructure-provisioning/src/general/lib/os/debian/notebook_lib.py, infrastructure-provisioning/src/general/lib/os/redhat/notebook_lib.py
Fixed repository for library dependencies (protobuf-compiler, snappy-devel).
Reduced compilation time - added cuda capability determination.
=> [EPMCDLAB-1019]: Fixed DeepLearning template on RedHat platform

infrastructure-provisioning/src/deeplearning/scripts/configure_deep_learning_node.py, infrastructure-provisioning/src/general/conf/dlab.ini, infrastructure-provisioning/src/general/lib/os/debian/notebook_lib.py, infrastructure-provisioning/src/general/lib/os/redhat/notebook_lib.py, infrastructure-provisioning/src/tensor/scripts/configure_tensor_node.py
Fixed LD_LIBRARY_PATH, Caffe runtest and updated NVIDIA driver version
=> [EPMCDLAB-1051]: Fixed Caffe on Deeplearning on RedHat platform

services/self-service/src/main/resources/webapp/src/app/reporting/toolbar/toolbar.component.css, services/self-service/src/main/resources/webapp/src/app/resources/computational/computational-resource-create-dialog/computational-resource-create-dialog.component.html, services/self-service/src/main/resources/webapp/src/app/resources/computational/detail-computational-resources/detail-computational-resources.component.html, services/self-service/src/main/resources/webapp/src/app/resources/manage-ungit/manage-ungit.component.ts, services/self-service/src/main/resources/webapp/src/app/resources/resources-grid/resources-grid.component.ts
Refresh active filter after new instance defined
=> EPMCDLAB-1103 | 1007 | 1003 | 1004

infrastructure-provisioning/src/deeplearning/scripts/configure_deep_learning_node.py, infrastructure-provisioning/src/general/conf/dlab.ini, infrastructure-provisioning/src/general/lib/aws/actions_lib.py, infrastructure-provisioning/src/general/lib/os/debian/notebook_lib.py, infrastructure-provisioning/src/general/lib/os/redhat/notebook_lib.py, infrastructure-provisioning/src/tensor/scripts/configure_tensor_node.py, infrastructure-provisioning/src/tensor/scripts/install_tensor_additions.py
Fixed Caffe2. Hardcoded stable library versions for Caffe/Caffe2, CNTK, MXNet, Theano, Keras
=> [EPMCDLAB-1099]: Fixed Caffe2 library compilation. Moved library versions to config.

services/self-service/src/main/resources/webapp/src/app/resources/computational/computational-resource-create-dialog/computational-resource-create-dialog.component.ts, services/self-service/src/main/resources/webapp/src/app/resources/resources-grid/resources-grid.component.ts
fixed issue with Validation for existing name of DataEngine Service/DataEngine
=> [EPMCDLAB-1272]: fixed issue with Validation

services/self-service/src/main/resources/webapp/src/app/resources/exploratory/install-libraries/install-libraries.component.css, services/self-service/src/main/resources/webapp/src/app/resources/exploratory/install-libraries/install-libraries.component.html
[EPMCDLAB-1269]: added type identifier for resources in libs INFO
=> Feature EPMCDLAB-1269

infrastructure-provisioning/src/general/files/aws/deeplearning_description.json, infrastructure-provisioning/src/general/files/aws/jupyter_description.json, infrastructure-provisioning/src/general/files/aws/rstudio_description.json, infrastructure-provisioning/src/general/files/aws/tensor_description.json, infrastructure-provisioning/src/general/files/azure/deeplearning_description.json, infrastructure-provisioning/src/general/files/azure/jupyter_description.json, infrastructure-provisioning/src/general/files/azure/rstudio_description.json, infrastructure-provisioning/src/general/files/azure/tensor_description.json, infrastructure-provisioning/src/general/files/gcp/deeplearning_description.json, infrastructure-provisioning/src/general/files/gcp/jupyter_description.json, infrastructure-provisioning/src/general/files/gcp/rstudio_description.json, infrastructure-provisioning/src/general/files/gcp/tensor_description.json
I've changed versions of notebooks in description JSON files for each cloud provider.
=> [EPMCDLAB-1318]: Updated description json files

infrastructure-provisioning/src/general/scripts/gcp/ssn_configure.py, services/self-service/src/main/resources/webapp/src/dictionary/gcp.dictionary.ts
Was added the new value 'shared_bucket_name' to ssn result.json
=> [EPMCDLAB-1321]: Fixed shared bucket for UI

infrastructure-provisioning/src/general/scripts/gcp/edge_configure.py, services/common/src/main/java/com/epam/dlab/dto/gcp/edge/EdgeInfoGcp.java, services/self-service/src/main/java/com/epam/dlab/backendapi/service/gcp/GcpInfrastructureInfoService.java
GCP bug fixing: shared bucket value now could be sent from ssn.json to Mongo DB.
=> Epmcdlab 1323

services/self-service/src/main/resources/webapp/src/app/resources/exploratory/exploratory-environment-create-dialog/exploratory-environment-create-dialog.component.ts, services/self-service/src/main/resources/webapp/src/dictionary/gcp.dictionary.ts
minor dictionary and input limits fixes
=> Bugfix epmcdlab 1332

infrastructure-provisioning/src/general/lib/gcp/meta_lib.py, infrastructure-provisioning/src/general/scripts/gcp/common_collect_data.py
[GCP]: Dataproc creation fails through string indices isn't integers
=> [EPMCDLAB-1340]: Fixed Dataproc creating & status check

services/self-service/src/main/java/com/epam/dlab/backendapi/dao/EnvStatusDAO.java, services/self-service/src/main/java/com/epam/dlab/backendapi/resources/callback/EnvironmentStatusCallback.java
=> [EPMCDLAB-1289] fixed bug with wrong status returning for de

services/self-service/src/main/resources/webapp/src/app/core/core.module.ts, services/self-service/src/main/resources/webapp/src/app/core/services/applicationServiceFacade.service.ts, services/self-service/src/main/resources/webapp/src/app/core/services/backup.service.ts, services/self-service/src/main/resources/webapp/src/app/core/services/healthStatus.service.ts, services/self-service/src/main/resources/webapp/src/app/core/services/index.ts, services/self-service/src/main/resources/webapp/src/app/health-status/backup-dilog/backup-dilog.component.html, services/self-service/src/main/resources/webapp/src/app/health-status/backup-dilog/backup-dilog.component.scss, services/self-service/src/main/resources/webapp/src/app/health-status/backup-dilog/backup-dilog.component.ts, services/self-service/src/main/resources/webapp/src/app/health-status/environment-status.model.ts, services/self-service/src/main/resources/webapp/src/app/health-status/health-status.component.html, services/self-service/src/main/resources/webapp/src/app/health-status/health-status.component.scss, services/self-service/src/main/resources/webapp/src/app/health-status/health-status.component.ts, services/self-service/src/main/resources/webapp/src/app/health-status/health-status.module.ts, services/self-service/src/main/resources/webapp/src/assets/styles/_theme.scss
=> feature EPMCDLAB-950

services/billing-aws/src/main/java/com/epam/dlab/BillingScheduler.java, services/billing-aws/src/main/java/com/epam/dlab/core/parser/ParserByLine.java, services/billing-aws/src/main/java/com/epam/dlab/module/aws/AdapterS3File.java, services/common/src/main/java/com/epam/dlab/process/ProcessInfoBuilder.java, services/common/src/main/java/com/epam/dlab/utils/ServiceUtils.java, services/common/src/main/java/com/epam/dlab/utils/UsernameUtils.java, services/provisioning-service/src/main/java/com/epam/dlab/backendapi/core/commands/CmdCommand.java, services/provisioning-service/src/main/java/com/epam/dlab/backendapi/core/commands/CommandExecutorMockAsync.java, services/provisioning-service/src/main/java/com/epam/dlab/backendapi/core/response/folderlistener/FolderListener.java, services/provisioning-service/src/main/java/com/epam/dlab/backendapi/core/response/folderlistener/WatchItem.java, services/security-service/src/main/java/com/epam/dlab/auth/core/UserInfoBuilder.java, services/security-service/src/main/java/com/epam/dlab/auth/dao/LdapUserDAO.java, services/security-service/src/main/java/com/epam/dlab/auth/dao/script/ScriptHolder.java, services/security-service/src/main/java/com/epam/dlab/auth/dao/script/SearchResultToDictionaryMapper.java, services/security-service/src/main/java/com/epam/dlab/auth/resources/LdapAuthenticationService.java, services/self-service/src/main/java/com/epam/dlab/backendapi/domain/ExploratoryLibCache.java, services/self-service/src/main/java/com/epam/dlab/backendapi/service/BackupService.java, services/self-service/src/main/java/com/epam/dlab/backendapi/service/BackupServiceImpl.java, services/self-service/src/main/java/com/epam/dlab/backendapi/service/ExploratoryServiceImpl.java
=> Revert "sonar issues fixed"

services/security-service/src/main/java/com/epam/dlab/auth/SecurityServiceApplication.java
=> Bugfix epmcdlab 1291

integration-tests/src/main/java/com/epam/dlab/automation/cloud/VirtualMachineStatusChecker.java, integration-tests/src/main/java/com/epam/dlab/automation/cloud/gcp/GcpHelper.java, integration-tests/src/main/java/com/epam/dlab/automation/helper/CloudHelper.java, integration-tests/src/main/java/com/epam/dlab/automation/http/ApiPath.java, integration-tests/src/main/java/com/epam/dlab/automation/model/CreateNotebookDto.java, integration-tests/src/main/java/com/epam/dlab/automation/model/ExploratoryImageDto.java, integration-tests/src/main/java/com/epam/dlab/automation/model/ImageDto.java, integration-tests/src/main/java/com/epam/dlab/automation/model/NotebookConfig.java, integration-tests/src/test/java/com/epam/dlab/automation/test/TestCallable.java, integration-tests/src/test/java/com/epam/dlab/automation/test/TestServices.java, integration-tests/src/test/java/com/epam/dlab/automation/test/libs/models/Lib.java
Added following functionality to integration tests for AWS and Azure:
- testing creation machine image from existing exploratory;
- testing creation notebook's copy from existing machine image with next comparison with original exploratory.
=> Image tests

integration-tests/examples/azure_templates/deeplearning/spark_cluster.json, integration-tests/examples/azure_templates/jupyter/spark_cluster.json, integration-tests/examples/azure_templates/rstudio/spark_cluster.json, integration-tests/examples/azure_templates/tensor/spark_cluster.json, integration-tests/examples/azure_templates/zeppelin/spark_cluster.json, integration-tests/examples/ec2_templates/deeplearning/spark_cluster.json, integration-tests/examples/ec2_templates/jupyter/spark_cluster.json, integration-tests/examples/ec2_templates/rstudio/spark_cluster.json, integration-tests/examples/ec2_templates/tensor/spark_cluster.json, integration-tests/examples/ec2_templates/zeppelin/spark_cluster.json, integration-tests/examples/gcp_templates/deeplearning/spark_cluster.json, integration-tests/examples/gcp_templates/jupyter/spark_cluster.json, integration-tests/examples/gcp_templates/rstudio/spark_cluster.json, integration-tests/examples/gcp_templates/tensor/spark_cluster.json, integration-tests/examples/gcp_templates/zeppelin/spark_cluster.json, integration-tests/src/main/java/com/epam/dlab/automation/helper/WaitForStatus.java, integration-tests/src/main/java/com/epam/dlab/automation/model/DeploySparkDto.java, integration-tests/src/test/java/com/epam/dlab/automation/test/TestServices.java
Fixed test's part of code incompatibility with previously updated Spark cluster creation parameters
=> Bugfix epmcdlab 1413

services/common/src/main/java/com/epam/dlab/mongo/IsoLocalDateDeSerializer.java
Changed local date deserializer
=> Changed return value according to current system zone offset.

services/self-service/src/main/java/com/epam/dlab/backendapi/resources/SchedulerJobResource.java, services/self-service/src/main/java/com/epam/dlab/backendapi/service/impl/SchedulerJobServiceImpl.java, services/self-service/src/test/java/com/epam/dlab/backendapi/service/impl/SchedulerJobServiceImplTest.java
Fixed scheduler's bug if a user didn't choose any of repeating days
=> Added possibility to fill scheduler's repeating days with all days of

infrastructure-provisioning/src/ssn/files/mongo_roles.json
Updated form of MongoDB roles for exploratory shapes fetching
=> Changed MongoDB roles for exploratory shapes fetching (role for each

infrastructure-provisioning/src/general/files/aws/deeplearning_Dockerfile, infrastructure-provisioning/src/general/files/aws/jupyter_Dockerfile, infrastructure-provisioning/src/general/files/aws/rstudio_Dockerfile, infrastructure-provisioning/src/general/files/aws/tensor_Dockerfile, infrastructure-provisioning/src/general/files/aws/zeppelin_Dockerfile, infrastructure-provisioning/src/general/lib/os/fab.py, infrastructure-provisioning/src/general/lib/os/redhat/notebook_lib.py, infrastructure-provisioning/src/general/templates/os/redhat/CentOS.repo
Fixed.RedHat(7.4) Installation Sparklyr and Tkinter for R-Studio.
=> [EPMCDLAB-1461]:Fixed.RedHat(7.4) Installation Sparklyr and Tkinter for R-Studio.

services/self-service/src/main/resources/webapp/src/app/resources/computational/computational-resources-list/computational-resources-list.component.html, services/self-service/src/main/resources/webapp/src/app/resources/computational/computational-resources-list/computational-resources-list.component.ts, services/self-service/src/main/resources/webapp/src/app/resources/resources-grid/resources-grid.component.html, services/self-service/src/main/resources/webapp/src/app/resources/scheduler/scheduler.component.ts
fixed issue with scheduler submission
=> [EPMCDLAB-1577]: disabled clusters actions if edge node is not active

infrastructure-provisioning/src/general/scripts/gcp/jupyter_dataengine-service_create_configs.py, infrastructure-provisioning/src/general/templates/azure/interpreter_spark.json, infrastructure-provisioning/src/general/templates/gcp/interpreter_spark.json
=> Fixed. Configure Dataproc on Jupyter. Added 'md' interpreter to Zeppelin template.

infrastructure-provisioning/src/general/lib/os/fab.py, infrastructure-provisioning/src/general/scripts/aws/dataengine-service_configure.py, infrastructure-provisioning/src/general/scripts/os/install_additional_libs.py
Add one more 'if' iteration for install_pip_pkg method. Priorities plugin on redhat emr-5.12 disabled.
=> [EPMCDLAB-1175 + 1570]

integration-tests/src/test/java/com/epam/dlab/automation/test/TestCallable.java, services/dlab-model/src/main/java/com/epam/dlab/dto/status/EnvResource.java, services/provisioning-service/src/main/java/com/epam/dlab/backendapi/core/commands/DockerCommands.java, services/provisioning-service/src/main/java/com/epam/dlab/backendapi/core/response/handlers/ComputationalConfigure.java, services/provisioning-service/src/main/java/com/epam/dlab/backendapi/resources/aws/ComputationalResourceAws.java, services/provisioning-service/src/main/java/com/epam/dlab/backendapi/resources/base/InfrastructureService.java, services/provisioning-service/src/main/java/com/epam/dlab/backendapi/resources/gcp/ComputationalResourceGcp.java, services/provisioning-service/src/main/java/com/epam/dlab/backendapi/service/SparkClusterService.java, services/self-service/src/main/java/com/epam/dlab/backendapi/dao/EnvStatusDAO.java
do not call status command for resources that have corresponding running containers
=> EPMCDLAB-1636

infrastructure-provisioning/src/base/scripts/install_prerequisites.py, infrastructure-provisioning/src/general/files/gcp/base_Dockerfile, infrastructure-provisioning/src/general/scripts/gcp/ssn_configure.py
Hot fix for SSN creation fails on process find oauth2client.client from GoogleCredentials
=> [EPMCDLAB-1660-1]: Add oauth2client lib to gcp ssn_configue

infrastructure-provisioning/src/base/scripts/install_prerequisites.py
=> [EPMCDLAB-1660-1]: Add oauth2client lib to install_prerequisites.py

infrastructure-provisioning/src/base/entrypoint.py
Changed entrypoint: json input now have higher priority than java input variables.
=> [EPMCDLAB-1654]: Changed priority from java input to json input file

services/self-service/src/main/resources/webapp/src/app/resources/computational/computational-resource-create-dialog/computational-resource-create-dialog.component.ts, services/self-service/src/main/resources/webapp/src/assets/styles/_general.scss
All EMR clusters run on spot 50% bit price by default
=> [EPMCDLAB-1691]: selected spot instances as a default state

infrastructure-provisioning/src/general/lib/os/debian/notebook_lib.py
Added 10 retry for spark cleanup method
=> [EPMCDLAB-1741]: Fix spark deploy on azure

infrastructure-provisioning/src/general/templates/os/redhat/ungit.service
Ungit new parameters usage for redhat
=> Ungit new parameters usage for redhat

infrastructure-provisioning/scripts/deploy_dlab.py, infrastructure-provisioning/src/deeplearning/scripts/configure_deep_learning_node.py, infrastructure-provisioning/src/edge/scripts/configure_nginx_reverse_proxy.py, infrastructure-provisioning/src/edge/templates/nginx.conf, infrastructure-provisioning/src/general/conf/dlab.ini, infrastructure-provisioning/src/general/lib/os/debian/edge_lib.py, infrastructure-provisioning/src/general/lib/os/fab.py, infrastructure-provisioning/src/general/lib/os/redhat/edge_lib.py, infrastructure-provisioning/src/general/scripts/aws/dataengine-service_configure.py, infrastructure-provisioning/src/general/scripts/aws/dataengine_configure.py, infrastructure-provisioning/src/general/scripts/aws/deeplearning_configure.py, infrastructure-provisioning/src/general/scripts/aws/jupyter_configure.py, infrastructure-provisioning/src/general/scripts/aws/rstudio_configure.py, infrastructure-provisioning/src/general/scripts/aws/tensor-rstudio_configure.py, infrastructure-provisioning/src/general/scripts/aws/tensor_configure.py, infrastructure-provisioning/src/general/scripts/aws/zeppelin_configure.py, infrastructure-provisioning/src/general/templates/os/debian/ungit.service, infrastructure-provisioning/src/general/templates/os/redhat/ungit.service, infrastructure-provisioning/src/jupyter/scripts/configure_jupyter_node.py, infrastructure-provisioning/src/rstudio/scripts/configure_rstudio_node.py, infrastructure-provisioning/src/tensor-rstudio/scripts/configure_tensor-rstudio_node.py, infrastructure-provisioning/src/tensor/scripts/configure_tensor_node.py, infrastructure-provisioning/src/zeppelin/scripts/configure_zeppelin_node.py
[REVERSE-PROXY-3]: Changed link list for notebooks description. Fix for rstudio-tensor notebook. Changed response for emr/spark. Fix ldap user validation. Fix ungit lniks/configuration.
=> Reverse proxy 3

infrastructure-provisioning/src/general/lib/os/fab.py, infrastructure-provisioning/src/general/scripts/aws/dataengine-service_configure.py
Fix Data Engine Service creation on GCP
=> Fix Data Engine Service creation on GCP

infrastructure-provisioning/src/general/lib/gcp/actions_lib.py
Fix Data Engine Service creation on GCP
=> Epmcdlab 1809

infrastructure-provisioning/src/general/lib/os/debian/notebook_lib.py, infrastructure-provisioning/src/general/lib/os/fab.py, infrastructure-provisioning/src/general/scripts/os/install_additional_libs.py
Fix new package name for newest kernel versions
=> Epmcdlab 1823

services/self-service/src/main/resources/webapp/src/app/management/management-grid/management-grid.component.html, services/self-service/src/main/resources/webapp/src/app/management/management-grid/management-grid.component.ts
on environments management page
=> [EPMCDLAB-1846]: prevent stop edge node during resource creation 

services/self-service/src/main/resources/webapp/src/app/resources/exploratory/install-libraries/install-libraries.component.ts
and RStudio with TensorFlow templates
=> [EPMCDLAB-1927]: prevented Java library installation for RStudio 

services/self-service/src/main/resources/webapp/src/app/health-status/backup-dilog/backup-dilog.component.ts, services/self-service/src/main/resources/webapp/src/app/resources/manage-ungit/manage-ungit.component.html, services/self-service/src/main/resources/webapp/src/app/resources/manage-ungit/manage-ungit.component.scss, services/self-service/src/main/resources/webapp/src/app/resources/manage-ungit/manage-ungit.component.ts
[EPMCDLAB-1966]: validation messages appearing fixes
=>  [EPMCDLAB-1967]: fixed issue with backup validity check

infrastructure-provisioning/src/general/lib/os/fab.py
Added possible prefix/suffix for cluster names, based on general templates of instance names during removing clusters from RStudio configuration files.
1. Fixed partly matches of cluster names
2. Simplified filtering of empty lines
=> [DLAB-108]: Fixed partly matches of cluster names

services/self-service/src/main/resources/webapp/src/app/core/services/applicationServiceFacade.service.ts, services/self-service/src/main/resources/webapp/src/app/health-status/health-status.component.ts, services/self-service/src/main/resources/webapp/src/app/health-status/manage-environment/manage-environment-dilog.component.html, services/self-service/src/main/resources/webapp/src/app/health-status/manage-environment/manage-environment-dilog.component.scss, services/self-service/src/main/resources/webapp/src/app/health-status/manage-environment/manage-environment-dilog.component.ts
- [EPMCDLAB-1999]: fixed issue after updating quota values by admin
=>  [EPMCDLAB-1908]: disabled stopping not active environments

services/self-service/src/main/resources/webapp/src/app/health-status/manage-environment/manage-environment-dilog.component.scss, services/self-service/src/main/resources/webapp/src/app/health-status/manage-roles-groups/manage-roles-groups.component.scss, services/self-service/src/main/resources/webapp/src/app/resources/exploratory/install-libraries/install-libraries.component.scss, services/self-service/src/main/resources/webapp/src/app/shared/modal-dialog/notification-dialog/notification-dialog.component.ts
=>  [EPMCDLAB-2005]: Manage role form fixes; quota validation fixes

services/self-service/src/main/resources/webapp/src/app/resources/computational/computational-resource-create-dialog/computational-resource-create-dialog.component.html, services/self-service/src/main/resources/webapp/src/app/resources/computational/computational-resource-create-dialog/computational-resource-create-dialog.component.scss, services/self-service/src/main/resources/webapp/src/app/resources/computational/computational-resources-list/computational-resources-list.component.ts, services/self-service/src/main/resources/webapp/src/app/resources/computational/computational-resources-list/index.ts, services/self-service/src/main/resources/webapp/src/app/resources/exploratory/ami-create-dialog/ami-create-dialog.component.ts
=> [DLAB-304]: fixed extra vertical scrollbar if check off the cluster configurations
